import React from 'react'
import { Row, Col } from 'react-bootstrap'

export const About = () => {
    return (
        <div style={{ marginTop: "20px" }}>
            <h1>Who We Are!</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique numquam fuga dolor dignissimos eaque voluptatibus excepturi deleniti itaque neque suscipit, fugit laborum facere, sint in pariatur porro amet recusandae, doloremque esse. Quis itaque in reprehenderit ullam facere sapiente id a aliquam natus, fugiat similique ratione quidem perferendis placeat! Mollitia recusandae deserunt totam illo culpa aspernatur. Impedit, incidunt. Inventore, iusto repellendus! Voluptatibus animi dicta consequuntur libero voluptatem dolorum tempora suscipit earum provident possimus pariatur perspiciatis, expedita ad itaque in exercitationem aliquid, ipsa quod inventore ipsam dolor? Tenetur necessitatibus natus quod cum officia exercitationem at non repellat tempora qui! Sapiente, odit repellendus?</p>

            <Row>
                <h2>Our Speciality</h2>
                <Col>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ratione iure provident, recusandae aut libero alias fugiat amet repellendus consectetur vel odit in animi harum sapiente, ad laudantium labore maiores aliquam dolores. Ex rerum laborum beatae fugiat quod porro eos deserunt, possimus optio iusto officia, laboriosam incidunt nobis? Architecto, eum nesciunt et laboriosam nulla dolor voluptatem quisquam a sequi, reprehenderit perspiciatis minima reiciendis animi consequatur placeat qui totam facilis excepturi. Doloribus assumenda enim omnis temporibus quidem quod! Dolores exercitationem, tenetur aliquam dolorem facere nostrum, numquam quibusdam modi ipsa, voluptatem earum blanditiis? Suscipit et labore officia soluta quis consequuntur doloremque distinctio?</Col>
                <Col>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ratione iure provident, recusandae aut libero alias fugiat amet repellendus consectetur vel odit in animi harum sapiente, ad laudantium labore maiores aliquam dolores. Ex rerum laborum beatae fugiat quod porro eos deserunt, possimus optio iusto officia, laboriosam incidunt nobis? Architecto, eum nesciunt et laboriosam nulla dolor voluptatem quisquam a sequi, reprehenderit perspiciatis minima reiciendis animi consequatur placeat qui totam facilis excepturi. Doloribus assumenda enim omnis temporibus quidem quod! Dolores exercitationem, tenetur aliquam dolorem facere nostrum, numquam quibusdam modi ipsa, voluptatem earum blanditiis? Suscipit et labore officia soluta quis consequuntur doloremque distinctio?</Col>
            </Row>
            <Row>
                <h2>Our Chefs</h2>
                <Col>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ratione iure provident, recusandae aut libero alias fugiat amet repellendus consectetur vel odit in animi harum sapiente, ad laudantium labore maiores aliquam dolores. Ex rerum laborum beatae fugiat quod porro eos deserunt, possimus optio iusto officia, laboriosam incidunt nobis? Architecto, eum nesciunt et laboriosam nulla dolor voluptatem quisquam a sequi, reprehenderit perspiciatis minima reiciendis animi consequatur placeat qui totam facilis excepturi. Doloribus assumenda enim omnis temporibus quidem quod! Dolores exercitationem, tenetur aliquam dolorem facere nostrum, numquam quibusdam modi ipsa, voluptatem earum blanditiis? Suscipit et labore officia soluta quis consequuntur doloremque distinctio?</Col>
                <Col>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ratione iure provident, recusandae aut libero alias fugiat amet repellendus consectetur vel odit in animi harum sapiente, ad laudantium labore maiores aliquam dolores. Ex rerum laborum beatae fugiat quod porro eos deserunt, possimus optio iusto officia, laboriosam incidunt nobis? Architecto, eum nesciunt et laboriosam nulla dolor voluptatem quisquam a sequi, reprehenderit perspiciatis minima reiciendis animi consequatur placeat qui totam facilis excepturi. Doloribus assumenda enim omnis temporibus quidem quod! Dolores exercitationem, tenetur aliquam dolorem facere nostrum, numquam quibusdam modi ipsa, voluptatem earum blanditiis? Suscipit et labore officia soluta quis consequuntur doloremque distinctio?</Col>
                <Col>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ratione iure provident, recusandae aut libero alias fugiat amet repellendus consectetur vel odit in animi harum sapiente, ad laudantium labore maiores aliquam dolores. Ex rerum laborum beatae fugiat quod porro eos deserunt, possimus optio iusto officia, laboriosam incidunt nobis? Architecto, eum nesciunt et laboriosam nulla dolor voluptatem quisquam a sequi, reprehenderit perspiciatis minima reiciendis animi consequatur placeat qui totam facilis excepturi. Doloribus assumenda enim omnis temporibus quidem quod! Dolores exercitationem, tenetur aliquam dolorem facere nostrum, numquam quibusdam modi ipsa, voluptatem earum blanditiis? Suscipit et labore officia soluta quis consequuntur doloremque distinctio?</Col>
                <Col>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ratione iure provident, recusandae aut libero alias fugiat amet repellendus consectetur vel odit in animi harum sapiente, ad laudantium labore maiores aliquam dolores. Ex rerum laborum beatae fugiat quod porro eos deserunt, possimus optio iusto officia, laboriosam incidunt nobis? Architecto, eum nesciunt et laboriosam nulla dolor voluptatem quisquam a sequi, reprehenderit perspiciatis minima reiciendis animi consequatur placeat qui totam facilis excepturi. Doloribus assumenda enim omnis temporibus quidem quod! Dolores exercitationem, tenetur aliquam dolorem facere nostrum, numquam quibusdam modi ipsa, voluptatem earum blanditiis? Suscipit et labore officia soluta quis consequuntur doloremque distinctio?</Col>
            </Row>
        </div>
    )
}
